name = "phosphor_lustre"
version = "1.0.0"

description = "A package of lustre compatible phosphor icons"
licences = ["Apache-2.0"]
repository = { type = "github", user = "brettkolodny", repo = "phosphor-lustre" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.3.2 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
